Fix/no account overwrite
loambuild/loam pull request #121
Opened 2024-07-18 20:40 UTC by BlaineHeffron

Temporary workaround while we wait for this to be fixed and released: https://github.com/stellar/stellar-cli/issues/1380

This makes it so that `generate` will not be run if the account already exists. I used `keys fund` because its the only command under `keys` that actually hits the network. Presumably if one is testing on a local instance of stellar then their local identity files might be out of date so using `fund` is the only way to guarantee they actually exist on the network that I'm aware of. If there is a better command to query the network for the existence of the key let me know and I will use that.

2024-07-18 20:43 UTC, willemneal requested changes

2024-07-18 20:43 UTC, willemneal commented on crates/loam-cli/src/commands/build/clients.rs
> +    async fn account_exists(account_name: &str) -> Result<bool, Error> {
You can use `Ok(..is_ok())`

2024-07-18 20:48 UTC, chadoh approved these changes
If you tried it out and it works as expected, then let's go!

2024-07-18 21:25 UTC, BlaineHeffron commented on crates/loam-cli/src/commands/build/clients.rs
> +    async fn account_exists(account_name: &str) -> Result<bool, Error> {
thanks, updated

2024-07-18 21:26 UTC, BlaineHeffron commented
Addressed Willem's comment, should be good to go!

2024-07-19 14:42 UTC, willemneal approved these changes

2024-07-19 14:42 UTC, merged